name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: git branch --track main origin/main
      - run: npx nx-cloud@next start-ci-run --distributes-on="6 rares-linux-large-js"
      - run: yarn install --frozen-lockfile
      - run: npx nx affected -t lint,build,test

